modLoader="javafml"
loaderVersion="[4,)"
license="Not specified"

[[mods]]
modId="optiminium"
version="0.1.0"
displayName="Optiminium"
authors="Dcchill"
description="An Optimization mod"
logoFile="logo.png"

# Start of user code block mod configuration
[[mixins]]
config="optiminium.mixins.json"
# End of user code block mod configuration

[[dependencies.optiminium]]
modId="neoforge"
type="required"
versionRange="[21.1.190,)"
ordering="AFTER"
side="BOTH"

[[dependencies.optiminium]]
modId="minecraft"
type="required"
versionRange="[1.21.1]"
ordering="AFTER"
side="BOTH"




# Start of user code block dependencies configuration
# End of user code block dependencies configuration
